environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
   - curl -kLO https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
   - 7z -offmpeg\bin e ffmpeg-release-full.7z "*\bin\*exe"
   - set PATH=%CD%\ffmpeg\bin;%PATH%

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover tests"
